[package]
name = "rust_integration"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_integration"
crate-type = ["cdylib"]

[dependencies]
numpy = { version = "0.29.0", features = ["nalgebra"] }
pyo3 = "0.29.0"

[patch.crates-io]
nalgebra = { git = 'https://github.com/McModknower/nalgebra.git', branch = 'fix/matrix-multiplication-row-major' }